name: make-lint
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: use Linter
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: true
      - run: make install
      - run: make lint